export enum SparePartCategory {
  MOTOR = 'MOTOR',
  FRENOS = 'FRENOS',
  SUSPENSION_DIRECCION = 'SUSPENSION_DIRECCION',
  TRANSMISION = 'TRANSMISION',
  FILTROS_FLUIDOS = 'FILTROS_FLUIDOS',
  ELECTRICO_LUCES = 'ELECTRICO_LUCES',
  CLIMATIZACION = 'CLIMATIZACION',
  CARROCERIA_ACCESORIOS = 'CARROCERIA_ACCESORIOS',
}
