-- No-op: migration 20260829192121_merge_hu11_hu12 already performed the full
-- PascalCase → snake_case conversion (drop old tables, create snake_case
-- tables, indexes and foreign keys).  This migration was auto-generated from
-- a different branch state and is entirely redundant.
