// BE-P02-6: fixed English status vocabulary for work orders (see MR !44).
export enum WorkOrderStatus {
  RECEIVED = 'RECEIVED',
  ASSIGNED = 'ASSIGNED',
  IN_DIAGNOSIS = 'IN_DIAGNOSIS',
  QUOTE_SENT = 'QUOTE_SENT',
  APPROVED = 'APPROVED',
  IN_REPAIR = 'IN_REPAIR',
  WAITING_FOR_PART = 'WAITING_FOR_PART',
  READY_FOR_DELIVERY = 'READY_FOR_DELIVERY',
  FINALIZED = 'FINALIZED',
  DELIVERED = 'DELIVERED',
  REJECTED = 'REJECTED',
}